### ISSUE TITLE
Polyfill does not satisfy complexity requirements

### ISSUE THREAD

**Issue by jfirebaugh** [medikoo/es6-map#8]
ES6 spec [says](http://www.ecma-international.org/ecma-262/6.0/#sec-map-objects):

> Map object must be implemented using either hash tables or other mechanisms that, on average, provide access times that are sublinear on the number of elements in the collection.

The polyfill in this module does not satisfy this requirement, as it uses a linear-time probe into an array for `get`, `has`, and `delete`.

**Comment by jfirebaugh** [comment]
I see this is expected behavior per #3. I agree with the commentators in that issue that this is an important caveat that should be documented, but I'll close this as a duplicate.

**Comment by medikoo** [comment]
@jfirebaugh thanks for understanding, it'll also be fixed with #2
