### ISSUE TITLE
Usage with ES6 import?

### ISSUE THREAD

**Issue by micros123** [medikoo/es6-map#9]
Could you clarify in your documentation whether this polyfill can be used with ES6 syntax? Most people using this are probably on ES6, so not using require anymore.
For example, the globally available syntax, could it be:

`import 'es6-map/implement';`

**Comment by medikoo** [comment]
What would be the use case of having this as ES module?

Mind this package is obsolete in environments which speak ES modules, as it's about bringing polyfill to ones that do not support `Map` natively and `Map` predates ES modules in features history
